### ISSUE TITLE
Add ability to fast-track applications

### ISSUE THREAD

**Issue by gsidebo** [mitodl/bootcamp-ecommerce#1010]
We have a need to immediately accept users into bootcamp runs without requiring them to complete all of the application steps (including payment). 

**Acceptance criteria**
- Some mechanism added to let admin users mark an application as immediately accepted (we could use the term "fast-tracked", "fast-track accepted", or something better/more descriptive).
  - UI element added to the application review screen
  - When an application is fast-track accepted, a `BootcampRunEnrollment` is created for the user and bootcamp run
  - State transitions added so that it is valid to transition to `COMPLETED` from any previous state
- **TBD**: For fast-tracked applications in the application dashboard, the "progress meter" UI (see: checkboxes in [this design](https://projects.invisionapp.com/d/main?origin=v7#/console/19928472/424654864/preview?scrollOffset=1544.4444580078125)) is updated to account for this new type of application progress.
  - Some options for this updated UI:
    1. Set all of the individual steps to have the green checkmark indicating that the step was completed, whether it was actually completed or not. If we go with this, we'll need to decide what to do with the detail text that goes in the steps that were skipped over (e.g.: "Last Updated: <date>")
    2. Display all of the completed steps, and completely omit the steps that were skipped over when the user was fast-tracked
    3. The same as option 2, but insert some fake "step" before the final "Application complete" step that explicitly states that the user was fast-tracked
- Any necessary changes applied to bootcamp BI queries to ensure that fast-tracked applications still show up as complete and the users still show up as enrolled in the given bootcamp run

**Comment by pdpinch** [comment]
Sometimes we only want to fast-track the applicant to `AWAITING_PAYMENT` so they can skip the video interview but they still need to pay. (e.g. [ZenDesk 87548](https://odl.zendesk.com/agent/tickets/87548))

**Comment by gsidebo** [comment]
I believe this is implemented now. You can set the `can_skip_application_steps` flag to fast-track users. You can check the implementation details for that in https://github.com/mitodl/bootcamp-ecommerce/issues/1166 and related issues
