### ISSUE TITLE
Wiretransfer: update data for existing orders

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#1033]
Sometimes we get incorrect or incomplete wire transfer data from the finance team. It would be convenient if we could run `import_wiretransfers` with the updated data and it would modify the existing orders (with appropriate auditing, of course).

**Comment by umarmughal824** [comment]
@pdpinch could you please a little bit more detail on it or could you provide a sample of that incomplete wire transfer data?

**Comment by pdpinch** [comment]
You should probably start by taking a look at the original wiretransfer epic, https://github.com/mitodl/bootcamp-ecommerce/issues/405 including the attached documents. 

I added an "incomplete" example to the [draft google sheet](https://docs.google.com/spreadsheets/d/19voIDC2K5vw4eD_pvrXupoOkSz_UVSIcevSFHtJN8Cc/edit#gid=0). The most common field to be missing is the "SAP doc # - Cash Application" which, in this case, has a value of "TBD". At some point the finance team would return to this sheet and update that with the correct value. 

The only place that field is stored is in the wiretransfer receipt table. You may need to discuss with @noisecapella a strategy for appropriately updating those records.

**Comment by umarmughal824** [comment]
@pdpinch does it only require updating the wire transfer receipt data?

**Comment by pdpinch** [comment]
> @pdpinch <https://github.com/pdpinch> does it only require updating the wire transfer receipt data
> 

To be safe, yes, we should only update the receipt data. 

Can I ask that you also include:

- a warning when the receipt data is updated
- a warning if any of the order data has changed
