### ISSUE TITLE
Support SAML login with staging config

### ISSUE THREAD

**Issue by gsidebo** [mitodl/bootcamp-ecommerce#1050]
Related to #1015 

Logging into NovoEd via SAML in two different environments leaves us open to issues where user ids/usernames exist in both environments. We need to alter the config so that properties coming from RC (our SAML staging environment) and production are reliably unique

**Comment by pdpinch** [comment]
@gsidebo did #1051 take care of this?

**Comment by gsidebo** [comment]
@pdpinch It did for new users. I'll close this and open a new issue for handling users that have an email that has already been used to log into NovoEd previously
