### ISSUE TITLE
switch from travis -> github actions

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#1081]
Travis will be limiting open source projects build time soon, so we need to transition to github actions.

Take a look at how we did it [open discussions](https://github.com/mitodl/open-discussions/pull/3204) and [micromasters](https://github.com/mitodl/micromasters/pull/4682).

**Comment by HamzaIbnFarooq** [comment]
Closed by https://github.com/mitodl/bootcamp-ecommerce/pull/1086
