### ISSUE TITLE
US8 As a financial admin, I want to prompt learners (by e-mail) to send the subsequent payments.

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#11]
### acceptance criteria
- [ ] Mailgun host set up
- [ ] e-mail templates
- [ ] integrate with per-bootcamp payment schedule

**Comment by pdpinch** [comment]
We'll send mail three times: a week in advance of the deadline, two days in advance and on the day of the deadline. 

I'll draft the e-mail templates.

**Comment by pdpinch** [comment]
I asked Andrea in finance for a copy of the e-mails they have been sending. We'll base our template off of that.

**Comment by pdpinch** [comment]
Draft e-mail templates at https://goo.gl/E8rSpn

**Comment by giocalitri** [comment]
How should this work? 
Right now if the user has never made a payment we have no idea if her existence (we do not keep any information locally).
Should we build a cache of the admissions?

**Comment by pdpinch** [comment]
For this issue, we should just send reminders to  users we know about -- users who have logged in and didn't pay the full price yet. 

At some point in the future we can look into trying to create accounts and send reminders for users who haven't logged in yet.

**Comment by giocalitri** [comment]
In the current situation, if an user has never paid for a class, we have no clue if s/he has ever been authorized to pay.
And even if s/he paid once, we do not know if currently s/he is authorized to pay: we can only assume it.

On May 2, 2017, at 6:43 PM, Peter Pinch <notifications@github.com<mailto:notifications@github.com>> wrote:

For this issue, we should just send reminders to users we know about -- users who have logged in and didn't pay the full price yet.

At some point in the future we can look into trying to create accounts and send reminders for users who haven't logged in yet.
