### ISSUE TITLE
Certificates: CMS interface for creating and editing certificate templates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#1101]
As a bootcamp admin, I need a way to create a certificate for a Bootcamp (run) and set the name and signatories on the certificate. 

Part of #1095 Certificates epic

### acceptance criteria

- [x] Certificate Template page is a child of Bootcamp (run) page in Wagtail
- [x] Required fields 
  - [x] Bootcamp title (required, needed in case it needs to be modified from the parent bootcamp) 
  - [x] Bootcamp subtitle (required)
  - [x] Bootcamp location (optional) 
  - [x] up to 5 signatories, each with a name, title and a signature image 

### out of scope

- Bootcamp certificates don't have CEUs like xPRO certificates
- We know that we will need to be able to support a modified template for bootcamp partners, but we don't know the scope of that yet.

**Comment by HamzaIbnFarooq** [comment]
Closed by https://github.com/mitodl/bootcamp-ecommerce/pull/1106 and https://github.com/mitodl/bootcamp-ecommerce/pull/1108
