### ISSUE TITLE
Certificates: add link to certificate from application dashboard

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#1102]
As a user, I need to have a link from my dashboard to my certificate

### Design 

https://invis.io/PGXCR7EMTKD#/417192809_Bootcamp_Dashboard_Dashboard_Collapsed

### Acceptance criteria

- [ ] Only display the link if there is both a certificate record for the user AND a certificate template
- [ ] This feature should be behind a feature flag so we can control when it is deployed

**Comment by HamzaIbnFarooq** [comment]
@pdpinch can you please provide the material-icon shown in the invisio link:
![image](https://user-images.githubusercontent.com/42243411/102994689-579c8b80-4541-11eb-811e-7f50c1a9fd48.png)

**Comment by pdpinch** [comment]
Took me a while to find it, but I believe this is it: https://material.io/resources/icons/?icon=history_edu&style=baseline
