### ISSUE TITLE
Certificates: user view

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#1103]
As a bootcamper, I need to be able to see my certificate, and share it with employers and social networks. 

Part of #1095 Certificates epic

### acceptance criteria

- [x] **IMPORTANT** the user view should be behind a feature flag
- [x]  unique URL based on UUID, same as xPRO
- [x] when the bootcamper is logged in, and viewing their own certificate, include sharing UI (same as xPRO)
- [x] print CSS omits header and footer and **prints on one page horizontally**
- [x] return a 404 when the certificate has been revoked

**Comment by HamzaIbnFarooq** [comment]
Closed By https://github.com/mitodl/bootcamp-ecommerce/pull/1116
