### ISSUE TITLE
Certificates: management command to create certificates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#1104]
As an bootcamp admin, I need a way to create certificates for all bootcampers who have earned a certificate. 

In most cases, this is every bootcamper who is enrolled. There is no grading criteria for bootcamps. 

Part of #1095 Certificates epic

### acceptance criteria

- [x] simple management command that takes a bootcamp run title of id as an input
- [x] created certificate records for all users with an enrollment in the bootcamp run

### related issues

- Management command for revoking an existing certificate for a specific user and bootcamp run
- Management command for blocking the creation of certificate for specific user and bootcamp run

**Comment by HamzaIbnFarooq** [comment]
@pdpinch  Acceptance criteria for this ticket has been covered by https://github.com/mitodl/bootcamp-ecommerce/pull/1111

Now we are only left with `Management command for blocking the creation of certificate for specific user and bootcamp run` we might need to create a separate ticket for that.
