### ISSUE TITLE
Certificate Template Design and Integration

### ISSUE THREAD

**Issue by asadiqbal08** [mitodl/bootcamp-ecommerce#1109]
part of #1095 

We need to update or redesign the `certificate_page.html` file according to bootcamp requirements. 

[2018 MIT HMS bootcamp certificate.pdf](https://github.com/mitodl/bootcamp-ecommerce/files/5715333/2018.MIT.HMS.bootcamp.certificate.pdf)
[Amit Singh Certificate.pdf](https://github.com/mitodl/bootcamp-ecommerce/files/5715334/Amit.Singh.Certificate.pdf)

A/C

- [x] Design the certificate page (Static Content)
- [x] Integrate the certificate context information into it. (Dynamic)
- [x] Print CSS omits header and footer and **prints on one page horizontally**

**Comment by asadiqbal08** [comment]
@pdpinch can you share the editable file of design because it would be easy to get the fonts details and other information.

**Comment by pdpinch** [comment]
I received updated designs today. I don't have an editable version, but this does include font information:

styles:

![MIT Bootcamp Style Sheet](https://user-images.githubusercontent.com/430126/102835330-5f82f100-43c4-11eb-8ccf-64af77bf4b9d.png)

MIT logo only:
![MIT Bootcamps Certificate IL_R1](https://user-images.githubusercontent.com/430126/102835324-5d209700-43c4-11eb-994f-c40d55fe37ca.png)

MIT + HMS logo:
![MIT HMS Bootcamps Certificate HI_R1](https://user-images.githubusercontent.com/430126/102835327-5e51c400-43c4-11eb-8849-e62bceb9d80f.png)

**Comment by pdpinch** [comment]
A couple things to note:

- [ ] The 2nd logo should be optional, and can be uploaded through the CMS. 
- [ ] The date is the Bootcamp run's end date
- [ ] I think I overlooked that we need a field for the granting institution(s). The default value can be "Massachusetts Institute of Technology" but we'll need to change for certificates like "MIT Bootcamps & Harvard Medical School Center for Primary Care"

**Comment by asadiqbal08** [comment]
@pdpinch can you take a look over the screens below ? any feedback over scss + html design ? 

## ONE:
![screencapture-file-Users-asadiqbal-Downloads-Archive-index-html-2020-12-22-16_47_40](https://user-images.githubusercontent.com/7334669/102885970-0d9aa380-4476-11eb-9c1e-bdf544033566.png)
## TWO:
![screencapture-file-Users-asadiqbal-Downloads-Archive-index-html-2020-12-22-16_49_11](https://user-images.githubusercontent.com/7334669/102885987-17240b80-4476-11eb-9939-f7609d6f47ec.png)
## THREE:
![screencapture-file-Users-asadiqbal-Downloads-Archive-index-html-2020-12-22-16_50_23](https://user-images.githubusercontent.com/7334669/102886002-1ab79280-4476-11eb-8c66-b2b384c077fe.png)
## FOUR:
![screencapture-file-Users-asadiqbal-Downloads-Archive-index-html-2020-12-22-16_50_48](https://user-images.githubusercontent.com/7334669/102886010-1ee3b000-4476-11eb-93ad-dad68a920e63.png)

**Comment by pdpinch** [comment]
Can we get five signatures on one line, like we have in the sample? Otherwise, this looks OK but I'm having trouble telling the difference between all the variations.

**Comment by pdpinch** [comment]
One thing that I want to confirm: users should be able to update their name by editing their full name in their profile (screenshot below). Does that work? 

<img width="1685" alt="image" src="https://user-images.githubusercontent.com/430126/102917401-2a71af80-4453-11eb-9ff2-1a2531e0b34a.png">

**Comment by HamzaIbnFarooq** [comment]
Closed by https://github.com/mitodl/bootcamp-ecommerce/pull/1116
