### ISSUE TITLE
Certificates: management command to block certificate creation for specified bootcampers

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#1135]
As a bootcamp admin, I often have a list of enrolled bootcampers who shouldn't get a certificate (typically because they dropped out before the bootcamp finished). 

I'd like to be able to block from these bootcampers from getting a certificate before I run ```python manage.py manage_certificates --generate-batch```

**Comment by asadiqbal08** [comment]
@pdpinch are you thinking to pass the list of enrolled bootcampers who shouldn't get a certificate along with the command ? or are you maintain the list elsewhere in database model ?

**Comment by pdpinch** [comment]
I'd like to run management commands something like:

```
python manage.py manage_certificates --block camper1@example.com camper2@example.com camper3@example.com
python manage.py manage_certificates --generate-batch
```

It's up to you where to store the data -- please make a suggestion.

**Comment by asadiqbal08** [comment]
@pdpinch I guess, you will run the command in that format then. 
```
python manage.py manage_certificates --generate-batch --block camper1@example.com camper2@example.com camper3@example.com
```

**Comment by asadiqbal08** [comment]
What about, If we define a boolean field in `BootcampRunEnrollment` as `user_blocked`. 
```
python manage.py manage_certificates --block camper1@example.com camper2@example.com camper3@example.com
``` 
the following format of command will just **update** the `BootcampRunEnrollment` model for the provided enrolled user list (if present in model). 

and then the command 
``` python manage.py manage_certificates --generate-batch``` will ignore the blocked user while filtering `BootcampRunEnrollment` model [here](https://github.com/mitodl/bootcamp-ecommerce/blob/master/klasses/utils.py#L51-L60). 

thought ?

**Comment by pdpinch** [comment]
That makes sense to me, but the field name should make it clear that the bootcamper is blocked from getting a certificate — perhaps `certificate_is_blocked` ? 

----------------
I am mobile.
