### ISSUE TITLE
Import Bootcamp Alums

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#1167]
### Goal: 
Sometimes, we would like to treat bootcamp users who have already attended a bootcamp differently from other users of the site. We need a way to keep track of who has completed a bootcamp. (For example #1166 )

### Background

For bootcampers who have been admitted since the site redesign in July 2020, we can use the enrollment table as a sign of alumni status. If the user was enrolled in the bootcamp, we can assume that they are alumni (since they paid and enrolled). For any alumni who paid and enrolled but did not complete the bootcamp, they should have the flag `user_certificate_is_blocked` set to True.

### Possibile implementation

For bootcampers from prior runs, we have a spreadsheet from the bootcamp team consisting of email addresses and bootcamp(s). Most of these emails, and most of these historical bootcamps will already be in our database. We can simply import the data, and create an entry in the enrollments table for each of them. 

If there are any missing bootcamp runs, we can just create them. 

For missing user accounts, we can create accounts for users, but without password and incomplete profiles. When the user attempts to login, they will have to use the “forgot password” feature to set a password, and then will need to complete their profile.

**Comment by umarmughal824** [comment]
@pdpinch this is the flow I have decided on, let me know if you have any concerns on that.

<img width="653" alt="Screenshot 2021-03-09 at 17 32 52" src="https://user-images.githubusercontent.com/4043989/110471142-97651f00-80fd-11eb-879e-8038ed90ce70.png">

**Comment by pdpinch** [comment]
To answer some of your questions:

> paid for the Bootcamp already or not?

If an email is on the list of alumni we are ingesting, you can assume that they paid. You can be an alum without paying. 

> completed the Bootcamp or not?

Same answer. You can't be an alum without having completed the bootcamp. 

> what is the structure of that spreadsheet?

I sent you a sample of what I have in mind. I don't have the final version from the course team yet.

**Comment by pdpinch** [comment]
I took a look at your flow diagram, and you're trying to do way too much. For this issue, we only want to ingest the data for past bootcamp alums, and reflect that in the bootcamp database. 

1. No need to write code for creating bootcamps. It would be better for the ingest (management?) command to error out if no matching bootcamp exists and I'll create it manually. 
2. don't create an application. The alums have already completed the bootcamp, there is no need to track application staus. 
3. we can assume they paid for the bootcamp they are an alum of. No need to check payment. 
4. no certificates

**Comment by pdpinch** [comment]
![image](https://user-images.githubusercontent.com/430126/110570537-09505f00-8124-11eb-9e51-d1841f454b1c.png)

**Comment by umarmughal824** [comment]
@pdpinch if we don't create an application then I am not sure how we will show it to the user. but we are only showing applications at the moment, but not enrolled courses. So in that case, there should be an application but with the completed status by default. 

I have mentioned the complete checking for payment and completion because It's written in the ticket description `For any alumni who paid and enrolled but did not complete the Bootcamp, they should have the flag user_certificate_is_blocked set to True.`

**Comment by umarmughal824** [comment]
As per my discussion with @pdpinch no need to create the application for the alumni.

**Comment by pdpinch** [comment]
@umarmughal824 I was talking to @gsidebo and he had some concerns about the requirement for creating users, since that is a complicated, multi-step process. Have you tested to see if "forgot password" works like I said it would in the description?

**Comment by umarmughal824** [comment]
> @umarmughal824 I was talking to @gsidebo and he had some concerns about the requirement for creating users, since that is a complicated, multi-step process. Have you tested to see if "forgot password" works like I said it would in the description?

yes @pdpinch its work that ways
