### ISSUE TITLE
Add a bootcamp_run_id to bootcamp run model

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#1173]
As a Bootcamp team member, finance team member and marketing team member, I need a unique identifier that can be used for each bootcamp run.

The identifier can be a string on the bootcamp run model, similar to what we do with edx_course_key in MicroMasters or cousreware_id in xPRO. 

The strings will be of the form "bootcamp-v1:TYPE+TOPIC-format+RUN" but we don't need to validate the contents. The course team will provide them for each past bootcamp run and any new bootcamp runs when they are created. 

### related issues 

- #1167 and PR #1171 import bootcamp alumns
- #1188 add ids to BI reports
- push bootcamp run ids to Hubspot to better distinguish between bootcamp runs

**Comment by arslanashraf7** [comment]
@pdpinch, Just a few quick queries while I'm working on this.

1) I'm assuming this field to be required and the initial value after the migration will be null/None and it will need to be set whenever a bootcamp run is created/updated moving on.
2) >add ids to BI reports

Can you add any pointers to point#2 regarding BI reports, is there some other repository or we'll need to change something in the code in bootcamp for BI.

**Comment by arslanashraf7** [comment]
@pdpinch, I was just checking the changes on RC and things look good but I think there is one thing that is still left for this ticket,
> add ids to BI reports


In order to add the run id to BI reports, Is this change going to be in bootcamps code? or we are going to have to add that in a separate repo.

**Comment by arslanashraf7** [comment]
Closing! Associated PRs(https://github.com/mitodl/bootcamp-ecommerce/pull/1178, https://github.com/mitodl/bootcamp-ecommerce/pull/1189) are merged & deployed!
