### ISSUE TITLE
Imported alums should not be blocked from getting a certificate

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#1182]
In issue #1167 / PR #1171 we added a management command to import alums and create enrollments for them. By definition, the alums we are importing have all earned a certificate for the bootcamp they enrolled in (if they did not earn a certificate, we would not be importing them). Therefore, the value of `user_certificate_is_blocked` should be False when they are imported. 

https://github.com/mitodl/bootcamp-ecommerce/blob/9840936e4c12a750b72117a41b5436bacc9686d9/profiles/api.py#L334

**Comment by umarmughal824** [comment]
@pdpinch after that removal, we have no other way to differentiate between the alumni and the normal user. So we will have to wait for https://github.com/mitodl/bootcamp-ecommerce/issues/1166 to get merged.

**Comment by pdpinch** [comment]
Ok, in that case, let's get #1166 functional and merged first before working on this.
