### ISSUE TITLE
Create management command to retire users

### ISSUE THREAD

**Issue by briangrossman** [mitodl/bootcamp-ecommerce#1185]
As an admin, I'd like a management command that can be used to retire an account, similar to the ones in [xPRO](https://github.com/mitodl/mitxpro/blob/master/users/management/commands/retire_users.py), [MicroMasters](https://github.com/mitodl/micromasters/blob/master/profiles/management/commands/retire_users.py) and [Open](https://github.com/mitodl/open-discussions/blob/master/profiles/management/commands/retire_user.py).

**Acceptance Criteria**
- [ ] set `is_active` on the account to False
- [ ] obfuscate the email address 
- [ ] obfuscate the password
- [ ] Question: Consider if there is any other data that needs to be altered
- [ ] Delete any social auth records

**Comment by pdpinch** [comment]
@rhysyngsun is this something that should be a part of https://github.com/mitodl/ol-django ?

**Comment by rhysyngsun** [comment]
I think probably no, our user/profile models differ a bit between applications and there are almost always other associated records we want to delete so it's best to just inline the command in each project.

**Comment by pdpinch** [comment]
I added a checkbox to delete social auth records, which I believe will remove any vestigial edX social auths. We should also remove any authentication for NovoEd -- but I'm not sure if that's stored in the social auth table or not.

**Comment by pdpinch** [comment]
We should also remove the user from Jobma as well, although I don't know how to do that.

**Comment by asadiqbal08** [comment]
Do we need to add in acceptance criteria this ? 
- Delete user bootcamp run enrollments

**Comment by briangrossman** [comment]
@asadiqbal08 

> Do we need to add in acceptance criteria this ?
> - Delete user bootcamp run enrollments

I don't think this is necessary for now. In xPRO, we don't remove enrollments. The user won't be able to access the bootcamp run enrollments... and keeping the enrollment will help ensure we have complete data.
