### ISSUE TITLE
Defer enrollment

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#1208]
Sometimes a bootcamper who has been admitted to and paid for a bootcamp run wants to defer to another bootcamp run.

We've done this manually so far (for example, https://odl.zendesk.com/agent/tickets/93651) but it would be best to have make this process repeatable, with a clear audit trail, similar to what we did in [xPRO](https://github.com/mitodl/mitxpro/blob/master/courses/management/commands/defer_enrollment.py).

### (suggested) acceptance criteria
- add a `change_status` status field to the enrollment model, with possible values of `deferred` and `refunded` (I don't think there are transfers in bootcamps)
- add an enrollment_audit model
- create a `defer_enrollment` management command similar to xPro that:
   - updates the status of the existing enrollment
   - creates a new enrollment with the same user and the new bootcamp run
   - update the order appropriately (I'm not exactly sure how we do this in xPRO, and whether it's appropriate for bootcamps) 

### Questions
- **Q:** bootcamp_application has a foreign key to the bootcamp_run. Should we update that as well?
 
### out of scope

- In xPRO, we have a google sheet integration that makes it possible for customer support to initiate an automated deferral without engineering intervention. Until we have more than a few of these, it's not worth the maintenance overhead of setting up the Google integration.

**Comment by umarmughal824** [comment]
@pdpinch I have a couple of questions

1. how a deferred enrollment Bootcamp application should be shown to the user in the dashboard
2. what if the user has paid for the micro Bootcamp with less price but he wants to defer to the program level bigger bootcamp whose price is way higher than what has already paid

So what do we need to do in all those cases?

**Comment by briangrossman** [comment]
@umarmughal824 

You should probably use xPRO as a model for how this should behave. Here's a link to the [defer_enrollment management command](https://github.com/mitodl/mitxpro/blob/master/courses/management/commands/defer_enrollment.py) for reference.

> 1. how a deferred enrollment Bootcamp application should be shown to the user in the dashboard

Since the user replaces one application/bootcamp with another, we can just show the new one in the dashboard and don't show the deferred one. (This is how xPRO behaves.)



>2. what if the user has paid for the micro Bootcamp with less price but he wants to defer to the program level bigger bootcamp whose price is way higher than what has already paid

In xPRO, we limit deferrals to runs for the same course. We should do the same for Bootcamps. Then you don't have to worry about the price because it's the same bootcamp. 

- Please ensure that deferrals are only allowed for the same bootcamp (but a different run). 
- Peter also had the good suggestion that you add a `--force` flag that lets you override this constraint.

**Comment by umarmughal824** [comment]
@pdpinch regarding your question, on deferring to the new Bootcamp run we gonna use the same application but along with that we need to update the bootcamp_run for that application. So the same application data could be used with the new bootcamp_run.

**Comment by umarmughal824** [comment]
> @umarmughal824
> 
> You should probably use xPRO as a model for how this should behave. Here's a link to the [defer_enrollment management command](https://github.com/mitodl/mitxpro/blob/master/courses/management/commands/defer_enrollment.py) for reference.
> 
> > 1. how a deferred enrollment Bootcamp application should be shown to the user in the dashboard
> 
> Since the user replaces one application/bootcamp with another, we can just show the new one in the dashboard and don't show the deferred one. (This is how xPRO behaves.)
> 
> > 1. what if the user has paid for the micro Bootcamp with less price but he wants to defer to the program level bigger bootcamp whose price is way higher than what has already paid
> 
> In xPRO, we limit deferrals to runs for the same course. We should do the same for Bootcamps. Then you don't have to worry about the price because it's the same bootcamp.
> 
> * Please ensure that deferrals are only allowed for the same bootcamp (but a different run).
> * Peter also had the good suggestion that you add a `--force` flag that lets you override this constraint.

thanks, @briangrossman that's enough for now.
