### ISSUE TITLE
Update to use the common libraries from mitol-django 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#1220]
We're trying to do a better job reusing common code across our projects. 

The library at https://github.com/mitodl/ol-django/tree/main/src/mitol/common is already used in mitxpro and ocw-studio. We should include it in bootcamps as well.

**Comment by umarmughal824** [comment]
@pdpinch that link is broken

**Comment by pdpinch** [comment]
You might need to talk with @rhysyngsun about how to use the mitdol/ol-django repo, but I updated the link: https://github.com/mitodl/ol-django/tree/main/src/mitol/common

**Comment by umarmughal824** [comment]
@rhysyngsun could you please give me a brief introduction about that as @pdpinch tagged you.

**Comment by rhysyngsun** [comment]
@umarmughal824, it's pip-installable: https://pypi.org/project/mitol-django-common/

Generally the common app has the most modern version of most things that show up in the main app, particularly models, utils, and envs. ocw-studio is probably the most integrated app at the moment since it fully uses it from the start

**Comment by umarmughal824** [comment]
@pdpinch @rhysyngsun I am on latest pip version `pip 21.1.2`. 

In the latest version of `mitol-django-common` we have pinned django to exact version `(==2.2.17)` which create a conflicts in installing as we are using different version `(==2.2.24)` of django in bootcamp. So we should update our requirements to remove that conflict.

https://github.com/mitodl/ol-django/blob/c469c3a9979ac7bc5fc20a29c91aa807cd970fb1/requirements.txt#L6

<img width="718" alt="Screenshot 2021-06-24 at 17 52 03" src="https://user-images.githubusercontent.com/4043989/123265890-f1ef8300-d514-11eb-8c55-aef9f7dbaaa4.png">

When I try to install older version of `mitol-django-common/`, it's say `No matching distribution found for mitol-django-common`.

<img width="723" alt="Screenshot 2021-06-24 at 17 45 09" src="https://user-images.githubusercontent.com/4043989/123265272-4cd4aa80-d514-11eb-95e7-95111953be33.png">

**Comment by rhysyngsun** [comment]
@umarmughal824 I pushed a new 1.1.0 version that supports a wider range of django versions and other dependencies as well: https://pypi.org/project/mitol-django-common/1.1.0/
