### ISSUE TITLE
Change NovoEd links to point directly to the desired course

### ISSUE THREAD

**Issue by gsidebo** [mitodl/bootcamp-ecommerce#1233]
_Depends on #1232 since SAML authentication will be broken until we fix that_

We currently link users to NovoEd using a hard-coded generic login link (setting name `NOVOED_SAML_LOGIN_URL`). It will be better UX to link users directly to the desired course, and we've been told by NovoEd that SAML authentication will continue to work. NovoEd course link template: `https://{novoed_url}/#!/courses/{novoed_course_stub}/home`. 

NOTE: We will only be able to test this on RC, and we should use the bootcamp run with the `novoed_course_stub` value of `test-bootcamp` ([admin link](https://bootcamp-rc.odl.mit.edu/admin/klasses/bootcamprun/3/change/)). 

**Acceptance criteria:**
- On RC, start and end dates for our test bootcamp run updated to reflect new end date for the equivalent course in NovoEd (7/31/2021; [bootcamp run admin link](https://bootcamp-rc.odl.mit.edu/admin/klasses/bootcamprun/3/change/); [NovoEd link](https://mitbootcamps.novoed.com/#!/courses/test-bootcamp/home))
- Links to NovoEd from the bootcamp dashboard go to `https://{novoed_url}/#!/courses/{novoed_course_stub}/home`
  - `{novoed_course_stub}` replaced with the `novoed_course_stub` value for the given BootcampRun
  - `{novoed_url}` replaced with the appropriate NovoEd URL. In production, that URL is `mitbootcamps.novoed.com`. In CI/RC, that URL is `mitstaging.novoed.com`.

**Comment by umarmughal824** [comment]
@briangrossman we don't have the context of `NovoEd'. Do we have any documentation for it?

**Comment by asadiqbal08** [comment]
Yup. not much context.

**Comment by gsidebo** [comment]
@asadiqbal08 @umarmughal824 NovoEd is a courseware provider that hosts some bootcamp content, and we have single-sign on configured with Bootcamps as the IdP and NovoEd as the SP 

Just FYI you don't need to test a successful link to NovoEd when you work on this. We can only test in deployed environments. All you will be doing in this issue is replacing a hard-coded link with a link that interpolates a bootcamp run variable. I can review, and we will test the functionality in RC.

Also FYI, our staging SSO config with them is broken, so we can't test on RC at the moment. This issue probably does not need to be addressed until we sort out that staging SSO config. I have an open ticket with them.

**Comment by gsidebo** [comment]
This is ready to work on now 👍
