### ISSUE TITLE
Fix warning message when running management commands

### ISSUE THREAD

**Issue by briangrossman** [mitodl/bootcamp-ecommerce#1262]
When you run management commands, you get the warning below. Please make the necessary changes to fix this warning.

```
System check identified some issues:

WARNINGS:
cms.SignatoryPage.signature_image: (wagtailcore.W001) Field hasn't specified on_delete action
	HINT: Set on_delete=models.SET_NULL and make sure the field is nullable or set on_delete=models.PROTECT. Wagtail does not allow simple database CASCADE because it will corrupt its tree storage.
jobma.Job.run: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
```

Note that you can get this to happen on RC using `retire_users`:
```
~ $ python manage.py retire_users --user=[username]
```

**Comment by asadiqbal08** [comment]
@briangrossman can you confirm the warning showing up --> `cms.SignatoryPage.signature_image`, that is related to wagtail, is coming up by this command? 
I mean, I did not notice any connection in `retire_users` command with wagtail CMS models.

Locally, I run:
```
./manage.py retire_users --user=admin2
```

**Comment by asadiqbal08** [comment]
But I find out that these warnings are related to models in CMS and Jobma application. I update the models and create migrations to resolve these warnings.

**Comment by briangrossman** [comment]
@asadiqbal08 

It looks like you might have found a solution. Regarding your question... the error was coming up with many (if not all) management commands. It doesn't necessarily need to be the `retire_users` command. That was just an example of a command that showed the error. 

Let me know if you have other questions.

**Comment by pdpinch** [comment]
Can this be closed?
