### ISSUE TITLE
Add terms and conditions

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#127]
Add text and a link to the payment page (/pay/) telling the user that "By making a payment I certify that I agree with the [MIT Bootcamps Terms and Conditions](https://docs.google.com/document/d/1Efr9zRMN6zWFWUtyqgJNn6ny2XxGkvXv17yupxTMF8U/edit)"

The text of the Terms and Conditions are currently in a Google Doc. We should extract those and put them on a separate terms page in the Bootcamps app.

**Comment by roberthouse54** [comment]
![image](https://user-images.githubusercontent.com/20047260/28677189-bade5aaa-72ba-11e7-8ae3-8a19418879

![bootcamp9 2x](https://user-images.githubusercontent.com/20047260/28677249-ea8ef764-72ba-11e7-8d7c-68e748fb7a55.jpg)
a5.png)
