### ISSUE TITLE
Forgot password should be case-insensitive

### ISSUE THREAD

**Issue by briangrossman** [mitodl/bootcamp-ecommerce#1295]
### Steps to Reproduce

- Register for an account on https://bootcamps.mit.edu/ (e.g. `youremail@gmail.com`)
- Sign out
- Click `Sign In`
- Enter your email (e.g. `youremail@gmail.com`)
- Click the `Forgot Password?` link
- Enter your email, but change the case for some of the letters (e.g. `YOureMAil@gMAil.com`)

### Expected Behavior

- Forgot password functionality will work and learner will be sent an email with a link to update their password

### Actual Behavior

- The learner sees a message that an email will be sent to them if an account with their email exists, but no email is sent.
![image](https://user-images.githubusercontent.com/21342568/131910607-78c2f59c-5cd0-45a8-8a02-d44c2aafe649.png)

- Note: when registering for the site, email addresses are not case sensitive.

### Related Issues
- https://github.com/mitodl/mitxonline/issues/147
- https://github.com/mitodl/mitxpro/issues/2304

**Comment by asadiqbal08** [comment]
@briangrossman are you sure the issue is really related to change in `case-sensitivity of letters` in email ? I mean, are you getting emails when you enter the `youremail@gmail.com` (as an example)

**Comment by briangrossman** [comment]
@asadiqbal08 Based on my testing, I am pretty certain it is related to the change in case.

For example, if your email is: `youremail@gmail.com`:
- `youremail@gmail.com` - This will send a password reset email
- `YoUremAil@gMail.com` - This will not send a password reset email

FWIW, this related issue was resolved by Wassaf on MITx Online: https://github.com/mitodl/mitxonline/issues/147
