### ISSUE TITLE
FluidReview webhook endpoint

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#136]
@pdpinch commented on [Wed Nov 15 2017](https://github.com/mitodl/odl-video-service/issues/365)

As an application reviewer, I would like to have users added to bootcamp ecommerce when they are accepted into a bootcamp. 

We can set up FluidReview to call a webhook on bootcamp-ecommerce when a user is accepted into a bootcamp (in FluidReview-speak, when their submission status changes to "accepted"). The call can include the user's email, FluidReview ID, submission (application) id and submission metadata, including price. 

### Acceptance criteria:
- [ ] webhook configured on FluidReview that sends user id, email, bootcamp (submission) and personal price
- [ ] When the webhook is executed, we need to:
  - [ ] create a user if one doesn't already exist
  - [ ] associate the user with a bootcamp klass
  - [ ] store the personal price

**Comment by noisecapella** [comment]
The user id, email and submission id are all available, I'm still investigating where the price information is

**Comment by pdpinch** [comment]
The surveymonkey folks have set up a sample trigger for us at https://mitbootcamps.fluidreview.com/admin/triggers/#edit/127456

They say it the sample payload includes DOB, User email, and cost.

**Comment by pdpinch** [comment]
George, I'm wondering now what, if any, other metadata we can reasonably retrieve, like the title of the bootcamp, title of the klass and klass dates.

**Comment by noisecapella** [comment]
It looks like `award.name` contains the title of the bootcamp (we should include `award.id` as a unique id`

**Comment by mbertrand** [comment]
@pdpinch the acceptance criteria described here seem to be covered by or dependent upon other issues for the most part: 
- create a user if one doesn't already exist -> #137 
- store the personal price -> #139 
- associate the user with a bootcamp klass -> consequence of #137?

Should I disregard these criteria in the PR review for this particular issue?

**Comment by noisecapella** [comment]
We still need to update the webhook itself with the right information

**Comment by pdpinch** [comment]
As @noisecapella says, PR #147 is only a partial solution to this issue.

**Comment by noisecapella** [comment]
Here's what the webhook currently looks like:

    {
    "date_of_birth": "{{ submission.var__155310__BzgWgZZxIk }}",
    "user_email": "{{ user.email }}",
    "amount_to_pay": "{{ submission.field__27006 }}",
    "user_id": "{{ user.id }}",
    "submission_id": "{{ submission.id }}",
     "award_id": "{{ award.id }}",
     "award_cost": "{{ award.field__27157 }}",
     "award_name": "{{ award.name }}"
    }

**Comment by noisecapella** [comment]
Here's an example request:

    {
      "date_of_birth": "",
      "user_email": "gschneel@mit.edu",
      "amount_to_pay": "",
      "user_id": 95195804,
      "submission_id": 4533767,
      "award_id": 81265,
      "award_cost": "1000",
      "award_name": "TEST CAMP"
    }
