### ISSUE TITLE
Personal Pricing

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#139]
As an application reviewer, I would like to be able to personalize applicants tuition price. This would allow for discounts and scholarships. 

The FluidReview application can be configured to add a price field to the submission metadata. When an applicant is accepted, the price field can be included in the webhook call to bootcamp-ecommerce. 

### acceptance criteria
- [ ] add a personal price field, perhaps to the `bootcampadmissioncache` model
- [ ] override the amount field in the installment model with this personal price
  (note that we are no longer planning to set up multiple installments for payment)

**Comment by mbertrand** [comment]
On the fluidreview test site, the webhook request includes fields `amount_to_pay` and `award_cost`.  Is `amount_to_pay` the personal price and `award_cost` the standard price?

**Comment by pdpinch** [comment]
We should check with @noisecapella but I believe that is correct: `award_cost` is the standard price (coming from the award object) and `amount_to_pay` is the person price, including any scholarships or other discounts.
