### ISSUE TITLE
Set up Mailgun domain for bootcamps-ecommerce

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#14]

**Comment by shaidar** [comment]
- Add new domain in mailgun - bootcamps.odl.mit.edu
- Add MX, TXT and CNAME records in AWS Route 53

**Comment by Ferdi** [comment]
Why dont we use one domain for all apps we build ?

**Comment by shaidar** [comment]
I believe having separate domains in mailgun for each app gives us the flexibility to apply different webhooks, establish separate mailing lists, see logs and reports per app.

**Comment by shaidar** [comment]
Discussed this in DevOps planning and it was agreed that there's no need for a separate domain and we'll just use the existing MM one.
