### ISSUE TITLE
Add country tax related fields to BI report 992 - Bootcamps Recognition

### ISSUE THREAD

**Issue by cachob** [mitodl/bootcamp-ecommerce#1439]
As a member of the Finance team, I'd like to be able to see on BI Report 992 (https://bi.odl.mit.edu/queries/992) what learners paid for the course/program, the tax, and total paid.

Here are the fields we need and their definitions:

unit_price - per cost of the course/program
discount - discount applied to learner
tax_amount - amount the learner was charged in taxes
tax_rate - the tax % applied to the transaction
total_paid - unit_price - discount + tax
ip_country code - 2 digit country code of where the learner is
ip_country - full country name of where the learner is
billing_country - the county from cybersource payment
billing_state

**Comment by pdpinch** [comment]
I don't think we should worry about this at this time.
