### ISSUE TITLE
Add `Renovate` to update dependencies

### ISSUE THREAD

**Issue by arslanashraf7** [mitodl/bootcamp-ecommerce#1441]
We have been shifted to renovate for most if not all of our other applications. We should configure renovate here as well so that our project dependencies can be updated automatically as per our `renovate` configuration.

**Reference:**
- xPRO
    - https://github.com/mitodl/mitxpro/pull/2680
- MITxOnline
    - https://github.com/mitodl/mitxonline/pull/1599  

Before starting, We need to verify if we should manually create this Renovate PR or if it's created through an automated mechanism. The reason I ask this is because the PR to enable `Renovate` in xPRO was automatic.

**Comment by blarghmatey** [comment]
I enabled Renovate on all repositories in the mitodl org. The onboarding PR for bootcamps is at https://github.com/mitodl/bootcamp-ecommerce/pull/1442
