### ISSUE TITLE
Write API specs for the bootcamp 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#15]
We need to provide some requirements for the Bootcamp Application developer for integrating with this bootcamp-ecommerce app. 

Roughly, we want to make a GET request with an email address. We should get a JSON response with a list of the bootcamps the user has been accepted into.

**Comment by pdpinch** [comment]
Ferdi and I have been in touch with Pavel, the developer of bootcamp.mit.edu. The API he develops can provide us with a primary key for each class the user has been accepted into.

**Comment by giocalitri** [comment]
We need the following API:

- given an user email, return the list of bootcamps where the user has been accepted.
    - REQUEST: 
        - GET `/<custom_base_url>/user/<user_email>`
    - RESPONSE: 
        - HTTP Headers : `Content-Type: application/json` 
        - Status codes: 
            - 200 OK
            - 400 - Bad Request: The given user email is not valid 
            - 401 - Unauthorized: Requesting client is not authenticated 
            - 403 - Forbidden: Requesting client is authenticated but there is no permission to query for progress for the given user email (not sure this is necessary). 
            - 404 - Not Found: requested user email doesn't exist
        - Example response
            - ``` 
               {
                   "user": "giovanni@example.com", 
                   "bootcamps" :  [
                        {
                            "bootcamp_id" : 23,
                            "bootcamp_title": "The Awesome Bootcamp",
                            "klasses" :  [
                                 {
                                     "klasse_id": 12,
                                     "klasse_name": "The Awesome Bootcamp Klasse of 2016",
                                     "status": "admitted"   // not sure about the actual statuses
                                 },
                                 {
                                     "klasse_id": 23,
                                     "klasse_name": "The Awesome Bootcamp Klasse of 2016",
                                     "status": "pending"   // not sure about the actual statuses
                                 }
                             ]
                        }
                        {
                            "bootcamp_id" : 76,
                            "bootcamp_title": "The Outstanding Bootcamp",
                            "klasses" :  [
                                 {
                                     "klasse_id": 36,
                                     "klasse_name": "The Outstanding Bootcamp Klasse of 2017",
                                     "status": "admitted"   // not sure about the actual statuses
                                 }
                             ]
                        }
                    ]
               }

**Comment by noisecapella** [comment]
@giocalitri Should `is_user_eligible_to_pay` be on the class level or the bootcamp level? Is a "klass" something specific to bootcamp?

**Comment by giocalitri** [comment]
bootcamp vs klass is the equivalent of course vs course_run in MM

**Comment by noisecapella** [comment]
Is it called "klass" in their documentation?

**Comment by giocalitri** [comment]
what documentation?

**Comment by pdpinch** [comment]
@giocalitri @noisecapella @Ferdi Is this done enough to share with Pavel?

**Comment by pdpinch** [comment]
This was shared with Pavel on 3/20. I'll open a follow up issue once he's completed the implementation.
