### ISSUE TITLE
Update BootcampAdmissionClient to look up admissions in WebhookRequest

### ISSUE THREAD

**Issue by noisecapella** [mitodl/bootcamp-ecommerce#151]
Blocked by #137 

We should:

 - add a field to `Bootcamp` saying whether we use the legacy admissions system for this bootcamp
 - update `BootcampAdmissionClient` to look up whether the user is admitted in `WebhookRequest` if the bootcamp is not a legacy bootcamp. I'm not sure if we should match up by email address or if there's another way to do it

**Comment by mbertrand** [comment]
How is the relationship defined between FluidReview objects and Bootcamps/Classes?  For instance, does a FluidReview award == a Bootcamp (as suggested by https://bootcampmit.fluidreview.com/admin/awards/) and if so does award id == bootcamp id?  What is the FluidReview equivalent of a Klass if any?

**Comment by mbertrand** [comment]
FluidReview award_id == Bootcamp klass_id

**Comment by mbertrand** [comment]
@pdpinch the legacy admissions API response includes an `is_user_eligible_to_pay` boolean attribute.  For fluidreview, `WebhookRequest` includes an `amount_to_pay ` attribute.  Should it be assumed that the user is always eligible to pay for the class in a `WebhookRequest`? Or eligible to pay as long as `amount_to_pay` is not null and/or > 0?

**Comment by mbertrand** [comment]
User in a `WebhookRequest` is always eligible to pay.

**Comment by mbertrand** [comment]
@noisecapella adding a field to `Bootcamp` to track whether it uses the legacy admissions system or not doesn't seem necessary to get this working.  The `BootcampAdmissionClient ` looks up info from the API by user email, and I'm guessing a user could be admitted to both legacy and non-legacy bootcamps.  So the `BootcampAdmissionClient` should probably always check both systems (by querying the legacy API and retrieving the award/klass ids from all `WebhookRequest` objects containing the user's email).  Does that sound good?
