### ISSUE TITLE
Don't use Mailgun to send Cybersource error notifications

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#164]
In the interest of simplicity, we should use the django core mail api instead of Mailgun for these CyberSource notifications. 

https://github.com/mitodl/bootcamp-ecommerce/blob/73acb0443e6eba5b58b359efb1b2a1982b729f97/ecommerce/views.py#L100

I think we could remove Mailgun altogether from this app once this is changed.

**Comment by gsidebo** [comment]
Removing mailgun isn't really an option after the recent updates to this app. Closing
