### ISSUE TITLE
When we receive a webhook with an unrecognized bootcamp/klass, create it

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#183]
Currently, we only process webhooks when the incoming `award_id` matches an existing `klass_id`. This puts an unnecessary configuration roadblock (i.e. me) in the way of creating new bootcamps  . 

We should be able to use the FluidReview award API to gather enough information to create the necessary bootcamp, class and installment. If there is data that isn't available, we can request the that it be added to the FluidReview schema. 

Since creating a new bootcamp is a significant change to the system, we may want to send an e-mail notification to the django admin address when they are created.

**Comment by mbertrand** [comment]
Currently, there isn't enough information in the webhook request body to correlate a new klass ('`award_id`') with a bootcamp. From the admin UI in FluidReview, I'm not even sure there's a clear distinction between bootcamp and klass in that system.  If not, then maybe we could assume that any new award_id/klass coming from FluidReview is also for a new bootcamp, and create both.

**Comment by pdpinch** [comment]
It's safe to assume that if an incoming award ID doesn't match a klass id, then a bootcamp and a klass (and installment) should be created. 

In practice, what I have been doing manually, is map the award name to bootcamp.title and the award description to klass.title. That seems to have worked well enough to satisfy the Bootcamp team. 

The one thing I'm still not sure about is the installment due date.

**Comment by pdpinch** [comment]
The installment due date should be one month prior to the bootcamp's start date.
