### ISSUE TITLE
Missing installment for a klass causes a blank page

### ISSUE THREAD

**Issue by mbertrand** [mitodl/bootcamp-ecommerce#193]
When a klass has no installment, the payment page is blank.  The payment page should either show that no payment is currently required, and/or raise an exception if no installment is found for a klass.

**Comment by pdpinch** [comment]
Do you know why the react error isn't getting raised to Sentry?

**Comment by mbertrand** [comment]
Not sure, there is a `sentry_client.js` javascript file being loaded on my local instance, which I think is what's required for Sentry frontend errors.  @blarghmatey @shaidar does the `SENTRY_DSN` config setting look right on heroku for production?   That gets passed to the javascript.
