### ISSUE TITLE
Add Google Tag Manager and differentiate payment success URL

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#196]
In order to track conversions across multiple sites (including Facebook), the bootcamp team would like to add google tag manager code to all the templates. Code is below.

They also need to have a unique URL to differentiate payment success from other views. Appending a query string will be sufficient to differentiate the URL, e.g. `/pay?payment-complete`. The redirect URL is specified at https://github.com/mitodl/bootcamp-ecommerce/blob/bbb0058467d4e6e129f0e6298df6a241a7145d12/ecommerce/views.py#L55 

This issues replaces #178

------------

## GTM CODE INSTRUCTIONS:

Paste this code as high in the `<head>` of the page as possible:

```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-TFSZHVB');</script>
<!-- End Google Tag Manager -->
```

Additionally, paste this code immediately after the opening `<body>` tag:

```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TFSZHVB"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by mbertrand** [comment]
After payment success, the URL already has parameters `status=receipt=&order=<order_id>`

**Comment by mbertrand** [comment]
@pdpinch does the payment amount need to be sent to GTM?

**Comment by pdpinch** [comment]
What URL is that specifically? If that's the API end-point, I don't think that will get exposed to GA

> After payment success, the URL already has parameters status=receipt=&order=<order_id>

**Comment by mbertrand** [comment]
@pdpinch it's `/pay?status=receipt&order=<order_id>`

**Comment by pdpinch** [comment]
Ok. It seem like that should work. 

I'm checking whether we need to pass the amount paid, but I think we've already covered that by POSTing it to FluidReview. 

> @pdpinch <https://github.com/pdpinch> it's /pay?status=receipt&order=<order_id>
