### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by noisecapella** [mitodl/bootcamp-ecommerce#20]
We need to add the relevant script tag for google analytics and whatever other analytics tools we use

for Prod, use UA-5145472-18
for CI and RC, use UA-5145472-19

**Comment by pdpinch** [comment]
This is blocked until we've settled on a domain for this web site.

**Comment by pdpinch** [comment]
don't forget to alert DevOps about adding the GA codes to the heroku settings.

**Comment by annagav** [comment]
The variables should be set now.
