### ISSUE TITLE
payment API returns 400 error when user payments exceed cost

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#207]
Sometimes the bootcamp team likes to roll additional charges into the program. They can do this by changing the price to pay in FluidReview and firing the web hook. 

Everything appears to work OK on the data side for us, but the payment API returns a 400 error when the user has paid more than the original bootcamp cost. 

I don't think we need to check this amount at all. If we must, then we really have to display a message to the user. I'm not sure what we were thinking here. 

See https://odl.zendesk.com/agent/tickets/16555 and https://odl.zendesk.com/agent/tickets/16556

**Comment by gsidebo** [comment]
@pdpinch Disabling the error is straightforward enough, but would we want to at least want to display some warning either after the user clicks submit, or as they type into the field?
