### ISSUE TITLE
Update documentation on dev environment for OS X

### ISSUE THREAD

**Issue by noisecapella** [mitodl/bootcamp-ecommerce#226]
https://github.com/mitodl/bootcamp-ecommerce/pull/218#issuecomment-418375696

In particular, remove the mention of docker-machine and link to the common application docs.

**Comment by pdpinch** [comment]
In particular, remove the mention of docker-machine and link to the common application docs.

**Comment by asadiqbal08** [comment]
Closing this in favor of [new ticket](https://trello.com/c/g4aP7IyX/67-need-to-update-the-readme)
