### ISSUE TITLE
inventory FluidReview APis

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#229]
As a dev, I'd like a list of all the FluidReview endpoints we are currently using, with a link to the code in question. 

After that, the next step is to review the [SMApply docs](docs.smapply.io/) to see how many of the same APIs exist in that app.

**Comment by annagav** [comment]
@pdpinch, what is the deliverable that would complete this task?

**Comment by pdpinch** [comment]
I updated the description with what I have in mind.

**Comment by annagav** [comment]
- List all users https://github.com/mitodl/bootcamp-ecommerce/blob/master/fluidreview/api.py#L288

- User info https://github.com/mitodl/bootcamp-ecommerce/blob/master/fluidreview/api.py#L231

- Award info https://github.com/mitodl/bootcamp-ecommerce/blob/master/fluidreview/api.py#L246

- Update amount paid by a user for a class when an order is fulfilled https://github.com/mitodl/bootcamp-ecommerce/blob/master/fluidreview/api.py#L318

**Comment by pdpinch** [comment]
What about authentication?

I opened a follow-up issue for mapping the APIs. Can you take a look at the checkboxes in #232 and let me know if I got everything?
