### ISSUE TITLE
SMApply end to end testing

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#234]
When the SMApply integration is complete, we will need to test the full workflow.

1. Submit an application into SMApply
2. Admit the applicant, with the default price
3. Confirm than an appropriate bootcamp was created in bootcamp.odl
3. Confirm that an appropriate user account was created in bootcamp.odl
4. Make a payment (and get it refunded)
5. Confirm that the FluidReview submission metadata was updated with the payment information
6. Repeat the above, but with a personalized price.

**Comment by pdpinch** [comment]
@annagav now that your code is deployed to RC, what settings do we need in Heroku to enable integration with SMApply?

**Comment by annagav** [comment]
@pdpinch, I don't think I have found a way in SMApply to set a personalized price.

**Comment by pdpinch** [comment]
I think we can close this now. We were able to test the personalized price.
