### ISSUE TITLE
Cybersource rejects HTML in bootcamp title

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#246]
After the changes in #225 we now allow webhooks from FluidReview & SMApply to set the title of bootcamps. Unexpectedly, we are finding HTML in the bootcamp names. Also unexpectedly, Cybersource rejects fields with HTML, returning a cryptic "You are not authorized" error.

We should just strip out any HTML tags before we pass it to Cybersource.

**Comment by pdpinch** [comment]
@annagav did you fix this already for SMApply?

**Comment by pdpinch** [comment]
The relevant models are here: https://github.com/mitodl/bootcamp-ecommerce/blob/master/klasses/models.py#L11

The payload for cybersource is generated here: https://github.com/mitodl/bootcamp-ecommerce/blob/master/ecommerce/api.py#L121

We don't get detailed errors from Cybersource, but based on circumstantial evidence, I think we need to make sure that `item_0_name` doesn't contain any HTML and is not empty (see #251). 

https://github.com/mitodl/bootcamp-ecommerce/blob/master/ecommerce/api.py#L151

**Comment by tasawernawaz** [comment]
@pdpinch thanks, I am taking a look.
