### ISSUE TITLE
SMApply tokens don't seem to refresh on expiration

### ISSUE THREAD

**Issue by mbertrand** [mitodl/bootcamp-ecommerce#248]
The SMApply OAuth token doesn't seem to be refreshing correctly after it expires, I had to recreate one manually to get it working again.  Relevant code is here: https://github.com/mitodl/bootcamp-ecommerce/blob/master/smapply/api.py#L62-L63

**Comment by pdpinch** [comment]
Since the tokens only last 2 hours, does that mean that the production system is dead in the water now?

Here are the (quite brief) docs on refreshing tokens: http://docs.smapply.io/#refreshing-a-token

It looks to me like we have the wrong endpoint for refreshing?

**Comment by mbertrand** [comment]
I think the endpoint is correct (`/api/v2/o/token/`) but the `auto_refresh_kwargs` values might need to be modified.

**Comment by mbertrand** [comment]
Can't duplicate this problem anymore with my latest token, so closing.
