### ISSUE TITLE
Cybersource purchase fails if bootcamp is missing description and/or dates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#251]
We were having an issue with a bootcamper trying to make a payment for the Deep Technology bootcamp. (See [ZenDesk #24466](https://odl.zendesk.com/agent/tickets/24466)). 

When they tried to make a payment, there were able to connect to Cybersource, but the payment failed with the message "your order was declined", similar to #246. 

After further investigation, I discovered that the Deep Technology Klass had an empty title and no values for start and end date. I filled those in, and was able to make the payment. 

I'm not sure, but I'm presuming that the issue is a missing Klass title. If that's an unavoidable issue with Cybersource, we should add some more validation to make sure the Klass has a title.

**Comment by pdpinch** [comment]
@tasawernawaz can you fix this at the same time as #246 ?

**Comment by tasawernawaz** [comment]
@pdpinch sure, I can take a look.
