### ISSUE TITLE
SMApply: when creating klass from webhook, we are populating klass.title with the wrong field

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#255]
It looks like we're using "Description" instead of "Title"

<img width="1583" alt="screen shot 2019-01-28 at 12 10 49 pm" src="https://user-images.githubusercontent.com/430126/51853447-52534980-22f6-11e9-9159-f5f9c5fa6e02.png">

I'm not sure if this is because the webhook is sending us the wrong value, or if we are requesting the wrong value from SMApply. 

Note: the bootcamp and the Klass can use the same title. They are no longer distinct concepts.

**Comment by tasawernawaz** [comment]
@pdpinch I didn't understand this issue, in screenshot we are trying to create klass and in title it looks like the issue is when creating bootcamp. Could you please add little more details to this.

**Comment by pdpinch** [comment]
I think you're right. When we create a bootcamp, we also create a klass for it. The klass description is getting the wrong value. It's ok if it reuses the title of the bootcamp. 

(this particular data structure of bootcamp/klass/installment is a legacy of an earlier implementation. It could be refactored into a single model, but we don't want to put the time in)

**Comment by tasawernawaz** [comment]
@pdpinch Can we have a hangout session to discuss this issue.

**Comment by tasawernawaz** [comment]
@pdpinch I can't reproduce this.

I have created bootcamp and tried to add `klass` and it always have empty `title` field regardless of what we have in bootcamp. Even we don't have any description field in bootcamp. Is there any chance that some has added long description in the wrong field for above `klass`.

I have tried to look at production but unfortunately I don't have access.

**Comment by pdpinch** [comment]
@annagav do you know how that super-long title got set in production? (I've since changed it, because it was Cybersource was rejecting it. So you won't see it currently)

**Comment by tasawernawaz** [comment]
fyi @annagav

**Comment by annagav** [comment]
@pdpinch The description of the award is used to populate the klass title. I think it was done based on this comment: https://github.com/mitodl/bootcamp-ecommerce/issues/183#issuecomment-363413959

**Comment by tasawernawaz** [comment]
@pdpinch Is this still an issue ?

**Comment by pdpinch** [comment]
Hm. I thought I replied to this, but I guess not. 

Yes, it's still an issue. When we create a klass from a webhook, we should populate klass.title with the award title not the description. This will be a duplicate of the content in bootcamp.title -- perhaps we will refactor these data models in the future.
