### ISSUE TITLE
SMApply API now sends "Basic" instead of "OAuth" in HTTP_AUTHORIZATION header

### ISSUE THREAD

**Issue by mbertrand** [mitodl/bootcamp-ecommerce#261]
This causes all webhook requests to be denied.  The WebhookPermission class for SMApply needs to be changed to expect "Basic" instead of "OAuth"

https://smapply.zendesk.com/hc/en-us/articles/360019234374-Release-Notes-February-28th-2019

**Comment by pdpinch** [comment]
This is working now
