### ISSUE TITLE
ValidationError: ["'' value must be a decimal number."]

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#264]
When we receive SMApply webhooks without a personal price ("Amount to Pay") they arrive as an empty string `""` which does not pass validation. We should be treating `""` the same as `None` 

https://sentry.io/organizations/mit-office-of-digital-learning/issues/930951075/?project=159445&referrer=github_plugin

```
DoesNotExist: PersonalPrice matching query does not exist.
  File "django/db/models/query.py", line 488, in update_or_create
    obj = self.get(**lookup)
  File "django/db/models/query.py", line 385, in get
    self.model._meta.object_name

InvalidOperation: [<class 'decimal.ConversionSyntax'>]
  File "django/db/models/fields/__init__.py", line 1554, in to_python
    return decimal.Decimal(value)

ValidationError: ["'' value must be a decimal number."]
(15 additional frame(s) were not displayed)
...
  File "smapply/api.py", line 208, in parse_webhook
    parse_webhook_user(webhook)
  File "smapply/api.py", line 283, in parse_webhook_user
    defaults={'price': personal_price}

Webhook 16 body is not valid JSON or has invalid/missing values.
```

**Comment by mbertrand** [comment]
Starting at line 283 the code is:
```python
        if personal_price is not None:
            user.klass_prices.update_or_create(
                klass=klass,
                defaults={'price': personal_price}
            )
        else:
            user.klass_prices.filter(klass=klass).delete()
```

The `personal_price` returned from the SMApply request (`https://applymitbootcamps.smapply.io/api/v2/awards/108444/metadata/44036/`) seems to be an empty string, not `None`, so the code tries to create/update a price with an invalid non-decimal value.

**Comment by pdpinch** [comment]
@tasawernawaz I think you have gotten this app running. If you need access to the SMApply test site, please talk to @annagav

**Comment by tasawernawaz** [comment]
@annagav I have created a PR #265 with the fix. However if I can get access to SMApply test site that can help me in future, and test this change as well.
