### ISSUE TITLE
When we receive a webhook, update the bootcamp stage

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#291]
Whenever we receive a webhook from SMApply, we should update the current stage of the bootcamper's application

### Acceptance criteria

- [ ] When we receive a webhook for a user and an award (klass), we should update the corresponding record in the personal price table
- [ ] With the current state of the app, these should all be in the "admitted" stage, since that is the only time we receive webhooks. 

### Questions

- **Q:** What values for the stage do we get from SMApply?

**Comment by annagav** [comment]
@pdpinch, I actually already addressed this in PR #299.

**Comment by annagav** [comment]
When we request 'application/{id}/` from smapply, there is a field `current_stage`:
```'current_stage': {'id': 195289, 'title': 'Admitted'},```

There are also other fields like `decision` which I think it the applicants decision info:
```'decision': {'applicant_decision': 0,
  'applicant_decision_deadline': None,
  'applicant_decision_required': False,
  'applicant_decision_submitted_on': None,
  'applicant_note': None,
  'awarded': '',
  'awarded_at': '2019-09-18T19:50:58',
  'created_at': '2019-09-18T19:50:58',
  'custom_fields': [],
  'decision': 0,
  'notification_message': '',
  'updated_at': '2019-09-18T19:50:58',
  'value': None,
  'visible': True},```

**Comment by pdpinch** [comment]
@annagav should we close this? Or are you saying there is more work to be done?

**Comment by annagav** [comment]
Yes, this is done. In my last comment I was just answering the question in the description.
