### ISSUE TITLE
Production Ready

### ISSUE THREAD

**Issue by noisecapella** [mitodl/bootcamp-ecommerce#3]
Off the top of my head this should include:
 
- [x] choose URL and configure DNS
- [x] Heroku and the build pipeline
- [x] Cybersource credentials 
- [x] Setting up Sentry
- [x] Mail monitoring

**Comment by blarghmatey** [comment]
This is the list from when we did this for Micromasters:

## "Production readiness" checklists

- [ ] Move to production dyno 
- [ ] Move db to production db
- [ ] #707 Move elasticsearch from bonsai to AWS
- [ ] #469 Performance Monitoring
- [ ] #980 Production error monitoring
- [ ] #1219 Mail Monitoring
- [ ] #1218 Load Testing
### Required features:
- [ ] Does it support configuration via environment variables?
- [ ] Does it support configuration via flatfile (e.g. YAML)?
- [ ] Does it have a sane default configuration (e.g. as close to a realistic production configuration as possible)?
- [ ] Does it run on parallel HTTP workers? (e.g. uWSGI, Gunicorn)?
- [ ] Does it log to standard out/error?
- [ ] Does it log to syslog?
- [ ] Can it send stack trace emails to a configurable email list?
- [ ] Does it have configurable log levels (e.g. DEBUG, ERROR, WARNING, INFO)?
- [ ] Does it have a test suite which measures code coverage?
- [ ] Does it have a status route (which requires a secret token) that can be used for health checking by a monitoring service?
- [ ] Does the health check validate that each service the app depends on is reachable (e.g. databases, caching, external APIs when necessary)?
- [ ] Does the health check return a response body with the availability information above in a machine-readable format in all cases?
- [ ] Does the health check return a 500 status code when any component in the health check is detected to be failing?
### Required documentation/service infrastructure:
- [ ] Does it have continuous integration builds which run the full test suite?
- [ ] Does it have an automated continuous delivery to a development environment?
- [ ] Does it have a documented release process?
- [ ] Does it's release process include staging and production builds, where staging builds are promoted to production?
- [ ] Does it's release process require that code changes be "signed off" as working on staging before being promoted to production?
- [ ] Does it have application/resource monitoring in production (e.g. New Relic agent, Zenoss SNMP)?
- [ ] Does it have service availability monitoring in production (e.g. periodic health checks with Zenoss or New Relic)?
- [ ] Does it have automated, periodically generated, fully restorable backups for each non-ephemeral data store in production?

(From https://github.com/mitodl/handbook/blob/master/production-ready.md)

**Comment by pdpinch** [comment]
No elastic search, I believe, in this app.

No need for load testing, I think.
