### ISSUE TITLE
Synchronize bootcamp stage with Hubspot Deal

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#304]
As a member of the marketing team, I need to know what stage of the application each user is in, so I can target reminders and other communication. 

We started tracking the application stage in the django application with PR #299. 

#### acceptance criteria

- [ ] everytime a bootcamp stage is updated, update the corresponding deal in hubspot

**Comment by pdpinch** [comment]
@sesterki @kyfantaz I think the way we left this was that we added a new property to the deal called `application_stage` and we sync that with the value of `personal_price.stage`

I still feel like Hubspot should be better than this, and I'd like to open a ticket with them. Can you share with me what you investigated so far and how it didn't work as expected? Or if you want to open a ticket yourselves and cc me that would be fine too.

**Comment by sesterki** [comment]
Essentially Hubspot does not support custom pipelines or custom deal stages (the stages of the pipeline) from the Ecomm Bridge API.

Permalink to a forum where a hubspot rep explains this:
https://community.hubspot.com/t5/APIs-Integrations/ECommerce-Bridge-Can-t-add-new-pipeline-stage/m-p/275180/highlight/true#M25041

**Comment by pdpinch** [comment]
I've confirmed this state of affairs again. We've worked around this issue by adding an additional field to the deal object that indicates the bootcamp application stage.
