### ISSUE TITLE
HUBSPOT_ID_PREFIX

### ISSUE THREAD

**Issue by mbertrand** [mitodl/bootcamp-ecommerce#307]
#### Summary

Describe where/how to generate these new values

- `HUBSPOT_ID_PREFIX ` - bootcamp-ci, bootcamp-rc, bootcamp

#### Applicable Environments

- [x] Apply configuration to CI
- [x] Apply configuration to RC
- [x] Apply configuration to Production

Done manually on all 3 for now

**Comment by pdpinch** [comment]
@mitodl/devops I think this is done? Feel free to close if you agree.
