### ISSUE TITLE
Being Able to Segment Applicants by Application Stage/Bootcamp

### ISSUE THREAD

**Issue by ChrisLanfranco** [mitodl/bootcamp-ecommerce#331]
Hi team,

We (bootcamps/marketing team) would like to be able to segment contacts and nurture them by the bootcamp and application stage of that particular bootcamp they're applying to. 

Right now we're running into a similar issue like xpro, where we were unable to segment contacts by the product they purchased (line items). For bootcamps though, we are unable to segment contacts by their application stage/by bootcamp. 

Let me know if you need additional info!

Thank you!
Chris

**Comment by pdpinch** [comment]
Hi Chris. I think I misunderstood this the first time I read it, so let's review the basics. 

1. Each bootcamp is set up as a product, so once an applicant has completed stage 1, you should be able to segment based on the deal they started. 

2. Each stage in the application process is mapped to a deal stage. When the application stage is updated, we updated the `application_stage` property of the deal. 

Have you examined this data in Hubspot? Where are the gaps?

**Comment by pdpinch** [comment]
After discussing this with Mariah, I think the solution here is to add a field to the deal in Hubspot to capture the bootcamp name. This will simplify the query for creating the segment so it doesn't have to join multiple tables.
