### ISSUE TITLE
set up DNS for bootcamp.odl.mit.edu

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#34]
In order to avoid a conflict with the DNS for the existing site at bootcamp.mit.edu, we won't use a subdomain. Instead, we'll go with `bootcamp.odl.mit.edu`. This should be a simple setup in Route 53 and Heroku.

**Comment by pdpinch** [comment]
I updated the description with the new name, a subdomain of odl.mit.edu.

**Comment by shaidar** [comment]
Added CNAMEs to Route53
