### ISSUE TITLE
Configure and deploy app on Heroku

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#35]

**Comment by shaidar** [comment]
Did the following:
- created bootcamp-ecommerce-ci based on [app.json](https://github.com/mitodl/bootcamp-ecommerce/blob/master/app.json) config
- created a heroku pipeline and added app to it
- connected app to GitHub and deployed it
- added team as collaborators

**Comment by shaidar** [comment]
Before app is full production, dynos for bootcamp-ecommerce would need to be changed from the free tier. I currently set it up with free dynos given that there's no point of paying at this point since we're not in prod yet.

**Comment by pdpinch** [comment]
Ok, I can access the site at the new name and it responds, but I can't log in -- the OAuth callback doesn't seem to work. @giocalitri I don't know if this is a configuration issue, or a bug or just something that hasn't been implemented yet.

**Comment by shaidar** [comment]
@pdpinch That's probably because none of the EDXORG_* config vars have been set.

**Comment by pdpinch** [comment]
Well, that would do it. =) Can you work with Giovanni to get those configured? I'm remembering now that we'll need to get some configuration done at edX as well. That will probably need a devops ticket and a little patience.

**Comment by giocalitri** [comment]
Not sure what's the status of this, but did you ask edX to create a new OAUTH application?
We need proper client id and secret.

**Comment by shaidar** [comment]
@pdpinch Sent in a request to edx about this and we're waiting to get needed credentials

**Comment by pdpinch** [comment]
https://openedx.atlassian.net/servicedesk/customer/portal/3/DEVOPS-5761

**Comment by pdpinch** [comment]
Blocked waiting for oauth credentials from edX

**Comment by giocalitri** [comment]
is this issue done?

**Comment by pdpinch** [comment]
The credentials appears to be working on -rc and production now.
