### ISSUE TITLE
US1: As a learner, I want to pay for my Bootcamp, the total amount or in a set of installments.

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#4]
Installments (i.e. payment price) are recommendations only. We don't need to enforce them. 

The Bootcamp team would like to set the size and number of installments per bootcamp, but to start with there will be 3 installments of $2000 each.

### acceptance criteria
- [x] ecommerce models
- [x] payment view
- [x] order fulfillment callback

**Comment by pdpinch** [comment]
@noisecapella is this blocked now, waiting for the keys from VPF?

**Comment by noisecapella** [comment]
It's blocked from completion, though there's still work to be done implementing the order fulfillment piece of it. That's what I'm working on now
