### ISSUE TITLE
Terms of Service

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#40]
Since we're using edX for SSO, I think we need a simple TOS page. 

I've drafted something based on the MicroMasters TOS: https://goo.gl/afL6sR

**Comment by pdpinch** [comment]
I think we need a quick design for this page -- or just some guidance on what template to use.

**Comment by roberthouse54** [comment]
We should add a link to the footer:

![image](https://cloud.githubusercontent.com/assets/20047260/26123362/a05fd8ac-3a48-11e7-9e20-2d37ce01c855.png)

Anf for the page, use a simple centered layout:

![image](https://cloud.githubusercontent.com/assets/20047260/26123394/bc4e6498-3a48-11e7-91b1-3f2316afe8db.png)

**Comment by gsidebo** [comment]
@roberthouse54 small layout issue: adding that TOS link with that text extends the necessary width to display all the footer links in one line. Before the phone breakpoint kicks in, the "Give to MIT" button is squeezed and pushes out of the viewable window. We could just allow the individual footer links to occupy their own line if the screen width gets squeezed, or we could just trim the link text. Let me know what you think

*Right before phone breakpoint:*
<img width="581" alt="ss 2017-05-17 at 10 33 53" src="https://cloud.githubusercontent.com/assets/14932219/26159359/681b66f6-3aec-11e7-9457-010373c9d009.png">

*Right after phone breakpoint:*
<img width="560" alt="ss 2017-05-17 at 10 34 03" src="https://cloud.githubusercontent.com/assets/14932219/26159372/6f4e78d2-3aec-11e7-825b-c439aace16bb.png">

**Comment by roberthouse54** [comment]
Is it possible to set the widths of those divs (left and right) as percentages, and then allow the links to break to two lines if the width is too small?
