### ISSUE TITLE
Display klass payments based on API results

### ISSUE THREAD

**Issue by gsidebo** [mitodl/bootcamp-ecommerce#41]
The bootcamp UI currently displays some hardcoded text for single klass that a user can pay for. We want to show the user the actual information from the API about the klasses they have paid for or can pay for.

Acceptance criteria:

- Payment page displays klass information based on API results
    - If user can pay for a single klass, show payment info/prompt for that klass (like [this design](https://projects.invisionapp.com/share/SFBD1T7DW#/screens/229728222))
    - If user can pay for a multiple klasses, show a dropdown with the options, and when one is selected, show payment info/prompt for that klass

This is the UI part of #6

**Comment by pdpinch** [comment]
@gsidebo have you started working on this?

**Comment by gsidebo** [comment]
been working on it for a couple days now. sorry! 😅
