### ISSUE TITLE
display modal when logging in to edX

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#49]
Similar to MicroMasters -- https://invis.io/Y4BG0Y3KP#/205088104_Sign_Up_Login_Modal -- display a modal before transferring the user to edX for login.

**Comment by pdpinch** [comment]
Blocked until we find out whether bootcamp.mit.edu has a terms of service, or if we have to make our own.

**Comment by giocalitri** [comment]
we are not going to do this
