### ISSUE TITLE
Account registration error

### ISSUE THREAD

**Issue by noisecapella** [mitodl/bootcamp-ecommerce#520]
Hopefully others can reproduce this:

 - Set `CYBERSOURCE_INQUIRY_LOG_NACL_ENCRYPTION_KEY` to some random value
 - Go to `/create-account`
 - Verify your email when it asks you to
 - Fill in your name and other information on the first page of the profile
 - You'll get a message saying that you cannot proceed: 
![Screenshot from 2020-05-14 16-32-16](https://user-images.githubusercontent.com/863262/81982910-83957d00-9600-11ea-91d5-c2360e45be4e.png)
 - Remove `CYBERSOURCE_INQUIRY_LOG_NACL_ENCRYPTION_KEY` and restart your docker containers
 - Go to `/create-account` and fill in the same email as before
 - Fill in the second page of the profile.
 - You'll get a second message, except there is a message in the query parameter saying that there's a missing state parameter:
![Screenshot from 2020-05-14 16-35-04](https://user-images.githubusercontent.com/863262/81983260-1209fe80-9601-11ea-851e-d295e711b26c.png)

**Comment by gsidebo** [comment]
@noisecapella Is this still relevant?
