### ISSUE TITLE
Refactor hubspot deal syncing

### ISSUE THREAD

**Issue by mbertrand** [mitodl/bootcamp-ecommerce#545]
The current code for syncing hubspot deals is based on the `PersonalPrice` model and assumes there is always a `PersonalPrice` for each bootcamp applicant.  This is no longer the case.  Hubspot deal syncing needs to be refactored.  Going forward, hubspot deals should be based off the `BootcampApplication` model and care should be taken to ensure that hubspot integrator objects ids for new deals do not overlap earlier ones based on personal price.

**Comment by Ferdi** [comment]
what will be the stages stages ?  are they different from the existing one  ?

**Comment by mbertrand** [comment]
The stages defined so far are here: https://github.com/mitodl/bootcamp-ecommerce/blob/b1cb17149bc5b65e2c4c3debac3fc5ac0fcc0d22/applications/constants.py#L14-L20
