### ISSUE TITLE
Update 404/500 pages

### ISSUE THREAD

**Issue by noisecapella** [mitodl/bootcamp-ecommerce#576]
We need to restyle our existing 404/500 error pages and change the contents (if necessary)

![Screenshot from 2020-05-27 17-13-26](https://user-images.githubusercontent.com/863262/83072840-75525280-a03d-11ea-81c8-31a660d38088.png)

**Comment by gsidebo** [comment]
@Ferdi @abdulkdawson If this isn't on your map already, we will need designs for the 404 and server error pages to bring it in line with the new site styling. We may also want to update the contents of those pages

**Comment by abdulkdawson** [comment]
@gsidebo I'll add those to my to-do list.

**Comment by gsidebo** [comment]
Closing in favor of #608
