### ISSUE TITLE
Remove deprecated pages and related code

### ISSUE THREAD

**Issue by noisecapella** [mitodl/bootcamp-ecommerce#616]
We have at least 2 pages that are being deprecated by the site redesign.
- The `/pay/` page
- The old index page (`index.html`)

We should get rid of those pages and any associated views and styling.

**NOTE:** The `/pay/` page was removed in #852, but that PR did not get rid of at least one API endpoint, and the old `Payment` component is still there (`static/js/components/Payment.js`). Please review that PR and make sure that all of the components/templates/endpoints/styles/etc. that are related only to the old payment page are removed.

**Comment by gsidebo** [comment]
@noisecapella I hope you don't mind me updating this issue to include removing the old index page. If you do, I'll create a new issue for that.

**Comment by noisecapella** [comment]
@gsidebo go for it
