### ISSUE TITLE
Blank page after payment on cybersource

### ISSUE THREAD

**Issue by giocalitri** [mitodl/bootcamp-ecommerce#65]
After the payment on cybersource the user gets redirected to the main website `https://bootcamp-ecommerce-ci.herokuapp.com/?status=receipt` but the page is empty.

Tested only on CI environment so far

**Comment by pdpinch** [comment]
I think this is a duplicate of #39

**Comment by giocalitri** [comment]
it's actually not: the reason is that we need to allow posts without CSRF token on the index page (see open PR)
