### ISSUE TITLE
Update SITE_NAME .env variable

### ISSUE THREAD

**Issue by mbertrand** [mitodl/bootcamp-ecommerce#664]
#### Summary

- `SITE_NAME`
  - "MIT Bootcamps" - production
  - "MIT Bootcamps CI" - CI
  - "MIT Bootcamps RC" - RC

#### Applicable Environments

- [x] Apply configuration to CI
- [x] Apply configuration to RC
- [x] Apply configuration to Production

**Comment by rhysyngsun** [comment]
@shaidar site name looks good on RC, could you apply to prod and close it out?

**Comment by shaidar** [comment]
Deployed in all envs. Closing issue.
