### ISSUE TITLE
Fix UI and show a meaningful message to the user in case there are no classes to pay

### ISSUE THREAD

**Issue by giocalitri** [mitodl/bootcamp-ecommerce#67]
right now we just do not show a payment box: we should probably say something like "you are not allowed to pay for anything at the moment".

We should also fix the UI:
<img width="1355" alt="screen shot 2017-05-11 at 9 51 30 am" src="https://cloud.githubusercontent.com/assets/1005204/25952844/c59354ae-362f-11e7-9da5-d812145d40fd.png">

**Comment by pdpinch** [comment]
@roberthouse54 how about "You have not been admitted to any bootcamps at this time. Please check back after you have been admitted"

**Comment by giocalitri** [comment]
I think that this is not accurate in case the user paid in the past and is not allowed to pay for anything at the moment.

**Comment by pdpinch** [comment]
So it's possible that the payment information for past bootcamps would appear below this message?

**Comment by giocalitri** [comment]
yes, in the light color area below

**Comment by roberthouse54** [comment]
How about: "No payment is required at this time."
