### ISSUE TITLE
Reflect new payment/installment logic in UI

### ISSUE THREAD

**Issue by gsidebo** [mitodl/bootcamp-ecommerce#71]
We've decided that the logic for payments and installments in bootcamp-ecommerce is as follows:

- A Klass should have one or more Installments
- The user will always see the total amount they've paid out of the total amount due, and will still be able to pay any amount towards the total at any time before the final Installment deadline
- The user will always see the date of the final deadline (i.e.: the last Installment deadline)
- If a user has not paid as much or more than the total amount up to and including the nearest future Installment amount, they will be shown a message that tells them how much they owe towards that amount, and that it is due by the Installment deadline date. EXAMPLE: A Klass has 4 Installments, $1000 each. 2 of those installments are in the past, the user has paid a total of $2500, and the next Installment has a deadline of May 30th. This message should indicate that the user needs to pay $500 by May 30th.
  - If a user has already paid more than the total amount required for the current Installment, this message will be hidden

We need to reflect this logic in the UI.

**Comment by gsidebo** [comment]
@pdpinch @Ferdi @roberthouse54 Please review

@roberthouse54: If you're going to create some designs for this, please link them here

@pdpinch @Ferdi - A few questions:

1. How should we handle a Klass with no Installments? I'm guessing we should just hide them from the user.
1. In terms of UI, what should we do if a user has not paid in full and has missed the deadline for the final Installment of a Klass? Again I'm assuming that the Klass will simply be hidden from the user.
1. If there are multiple Installments for a Klass, should we include some special messaging when users are paying toward the final Installment of the series? We're treating Installments as a sort of informal concept, i.e.: you can miss an Installment and still pay/enroll in the Klass if the final Installment deadline hasn't passed. Since the final Installment deadline is the "real" deadline, I'm wondering if we should include some special messaging.
1. We need to think about the scenario where a user pays for and Installment in full, and other Installments still exist in future. Should we provide some way for the user to pay the total amount for all of the Installments? If not, what do we show the user? Do we hide the payment form since they've paid for that Installment fully and the next Installment period hasn't yet begun?

**Comment by gsidebo** [comment]
@roberthouse54 updated

**Comment by pdpinch** [comment]
1. If there are no installments, can we just show the final deadline?
2. It's ok to hide / prevent payments once the final deadline has passed. If that's not the right solution, we will cross that bridge when we come to it.

**Comment by gsidebo** [comment]
@pdpinch My understanding is that there is no deadline without an Installment. I don't think we store information about deadlines in any other place

**Comment by pdpinch** [comment]
1. If that's the case, then I agree, let's hide a klass with no installments/deadlines. That's a configuration issue that will be addressed as soon as we realize no one can pay.

**Comment by Ferdi** [comment]
The main description looks good to me.   Re 1)  please assume that all klasses have installments/deadlines

**Comment by gsidebo** [comment]
Updated language for payment deadlines from @roberthouse54:

![updated_payment_deadline_copy](https://cloud.githubusercontent.com/assets/14932219/26064230/554b5804-395e-11e7-9277-e6e7e6b6f77d.png)

**Comment by gsidebo** [comment]
Some specific questions: 

1. @pdpinch @roberthouse54 Have we decided on what to show if a user missed an intermediate installment deadline, but has not yet missed the final one?
1. @giocalitri I'm wondering if we should add some logic on our end to handle a case where the external bootcamp API gives us a klass that is considered payment-eligible, but has an end date in the past. Can we depend on the external bootcamp API to not return any bootcamp klasses like that?

**Comment by roberthouse54** [comment]
I think we should say: 

"You missed the first payment deadline. A total downpayment of $3000 is due by Oct. 10, 2017".

**Comment by gsidebo** [comment]
If that's what we're going with, I would prefer 'You missed the _previous_ payment deadline'. Then we don't need to worry about changing 1 -> 'first', 2 -> 'second', etc. Any extra UI decoration with that missed-payment message? Italics, font color, etc...

**Comment by roberthouse54** [comment]
That sounds fine to me. I do not particularly want any extra styles associated with it.
