### ISSUE TITLE
Update and streamline button styling

### ISSUE THREAD

**Issue by gsidebo** [mitodl/bootcamp-ecommerce#747]
We have many buttons on the site, and we have some styles to add and some possible inconcistencies to address. In general, we need to do 2 things: (1) add hover/clicked styling to buttons, (2) combine the styling of several button types that are arbitrarily different.

### Streamline styles

- We have 2 reds for buttons on the site: those with the `btn-danger` bootstrap class (hex `#dc3545`), and those styled by our CSS (hex `#ec654d`). `#ec654d` should be used for all of these buttons
  - **Nice to have**: Get rid of "btn-danger" on all of the relevant buttons since none of them are doing anything "dangerous". If we're going to use a bootstrap class, it should be one that more accurately describes these buttons. We would need to override the default bootstrap colors in that case.

### Hover/clicked styling

- Red bg buttons (e.g. auth forms, "Apply Now"): use #A02B2F for the background/border when hovered or clicked
- White bg buttons (e.g. "Select Bootcamp" in app dashboard): use ??? when hovered or clicked
- Grey buttons ("Sign In"/"Create Account"/"Sign Out" in navbar): use ??? when hovered or clicked

**Comment by gsidebo** [comment]
@abdulkdawson Can you clarify the the two "???"s in the description? Need to know what should happen when red-border-white-background buttons and grey-background buttons are hovered/clicked

**Comment by abdulkdawson** [comment]
The Red border white background button should fill red when hovered and clicked. The grey background button should darken when hovered. The hovered hex value is #333333.

**Comment by asadiqbal08** [comment]
@gsidebo can you add the Acceptance criteria section above ?
