### ISSUE TITLE
Accessibility audit

### ISSUE THREAD

**Issue by gsidebo** [mitodl/bootcamp-ecommerce#748]
We need to go through the site to check for and fix any accessibility issues.

Known issues:
- We have anchor tags that will probably need aria attributes, particularly the ones that have no `href` that we are using as buttons

**Comment by pdpinch** [comment]
@briangrossman did a review already and I think we addressed everything he saw, except for the application review app which is admin only. 

@gsidebo did we overlook anything that you know of?

**Comment by gsidebo** [comment]
@pdpinch There was just one specific issue I had in mind, but it might already be solved. The "Expand"/"Collapse" anchors in the application dashboard are using a custom component that takes care of tabbing/key press, but they [don't use the `aria-expanded` attribute](https://www.accessibility-developer-guide.com/examples/sensible-aria-usage/expanded/). I think we need to add that attribute at least. Not sure if there are any other attributes (for example, any that might need to be added to the tag that contains the content that is expanded by that button). I summon our foremost accessibility-knowledge-haver – @aliceriot do we just need to add `aria-expanded` to that anchor in order to follow the accessibility best practices? [Here's the code](https://github.com/mitodl/bootcamp-ecommerce/blob/master/static/js/pages/applications/ApplicationDashboardPage.js#L279-L286) if it helps

**Comment by aliceriot** [comment]
yeah I think for that since it's not a browser-native element that's providing the expand / collapse behavior we want to do some aria stuff

**Comment by aliceriot** [comment]
the links should also maybe have `aria-role="button"` in this use-case although I'm not sure (I am far from an accessibility expert :P)

**Comment by aliceriot** [comment]
so I think the proper thing to do here is just to not use `<a>` tags, since what we're using them for here is really properly a button. Accordingly, going to switch them over to be buttons!

**Comment by aliceriot** [comment]
react also throws an error if you put `aria-role="button"` on to an `<a>` tag

**Comment by aliceriot** [comment]
I switched these elements all over to use `<buttons>`, and added a new `.borderless` class which we can apply to buttons which styles them link links (`display: inline`, `border: none`, `padding: 0`, `background: none`, etc)
