### ISSUE TITLE
Resource Page: Hero image should be optional

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#761]
Pages like "Privacy Policy" may not have a hero image. It should be optional.

Currently on RC, when there is no hero image, the top nav doesn't render. The top nav should always render.

**Comment by pdpinch** [comment]
@asadiqbal08 I think you already took care of this?

**Comment by asadiqbal08** [comment]
yes. Corresponding to https://github.com/mitodl/bootcamp-ecommerce/issues/693
