### ISSUE TITLE
Bootcamp dropdown menu styling is too subtle

### ISSUE THREAD

**Issue by noisecapella** [mitodl/bootcamp-ecommerce#766]
Not sure how important this is, but it seems like there should be more of a distinction between the selected and unselected bootcamps in the select bootcamp menu. In this pic the first item is being hovered over with the mouse cursor.

![bootcamp_selector](https://user-images.githubusercontent.com/863262/85619631-94d69e00-b630-11ea-8384-07802ef84eeb.png)

**Comment by abdulkdawson** [comment]
@noisecapella use this hex value #D8D8D8 to distinguish between selected and unselected preferably for the selected item.

**Comment by gsidebo** [comment]
FYI this is being address as part of #658
