### ISSUE TITLE
If an application has no submission steps, the user can't proceed from the resume step to the payment step

### ISSUE THREAD

**Issue by noisecapella** [mitodl/bootcamp-ecommerce#773]
I don't know that it's a blocker for us since we have submission steps for our upcoming bootcamps, but maybe something we should address just in case

**Comment by briangrossman** [comment]
@noisecapella - `The Prophet`

Closed with:
- https://github.com/mitodl/bootcamp-ecommerce/issues/1269
- https://github.com/mitodl/bootcamp-ecommerce/issues/1289
