### ISSUE TITLE
Show bootcamp title + klass title in the `/pay` 

### ISSUE THREAD

**Issue by giocalitri** [mitodl/bootcamp-ecommerce#78]
Right now we just show the klass title but looking at the real data, it does not make much sense.

**Comment by Ferdi** [comment]
Can we please show ```"Bootcamp_title," + "start_date -" + "end_date" + "location"```

like 

"Internet of Things, May 29 - June 3 2017, Cambridge, MA, USA"

**Comment by giocalitri** [comment]
We do not have the bootcamp location, but we can definitely stop using the klass title and put start and end date.
