### ISSUE TITLE
React warning on resume drawer open

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/bootcamp-ecommerce#780]
This is probably related to the dropzone library we're using.

I see this error logged when I open the drawer to upload my resume:
> Each child in a list should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in label
    in O
    in div
    in n
    in t (created by ResumeUploader)
    in ResumeUploader (created by ResumeLinkedIn)
    in div (created by ResumeLinkedIn)
    in ResumeLinkedIn (created by ConnectFunction)
    in ConnectFunction (created by Drawer)
    in div (created by DrawerContent)
    in DrawerContent (created by Drawer)
    in aside (created by DrawerRoot)
    in DrawerRoot (created by ModalDrawer)
    in ModalDrawer (created by Drawer)
    in Drawer (created by Drawer)
    in span (created by ThemeRoot)
    in ThemeRoot (created by Theme)
    in Theme (created by Drawer)
    in Drawer (created by App)
    in div (created by App)
    in App (created by ConnectRequestFunction)
    in ConnectRequestFunction (created by ConnectFunction)
    in ConnectFunction (created by HOC)
    in HOC (created by Context.Consumer)
    in Route
    in ScrollToTop (created by Context.Consumer)
    in withRouter(ScrollToTop) (created by Router)
    in Router (created by Router)
    in Provider (created by Router)
    in Provider (created by Router)
    in Router
    in AppContainer

**Comment by gsidebo** [comment]
Closing in favor of https://github.com/mitodl/bootcamp-ecommerce/issues/901
