### ISSUE TITLE
HomePage on CI is broken

### ISSUE THREAD

**Issue by noisecapella** [mitodl/bootcamp-ecommerce#784]
However it's working on RC so it may not be critical to MVP if we can just fix the home page configuration in the database

**Comment by pdpinch** [comment]
Doesn't look totally broken to me, but there's plenty of missing content. We should copy back the content from RC

**Comment by umarmughal824** [comment]
@pdpinch both of the pages seem alike. I have checked it now.

**Comment by asadiqbal08** [comment]
Replicated the HomePage contents from RC to CI (https://bootcamp-ecommerce-ci.herokuapp.com/). 
anyone can verify it ?

**Comment by asadiqbal08** [comment]
@noisecapella  @pdpinch  any update over it ? Can I close it ?

**Comment by pdpinch** [comment]
I'm getting 500 errors trying to load the images on the home page. I think this happened before, but I don't remember the solution. 

For example, https://bootcamp-ci.odl.mit.edu/images/3fGSOcMgMVRZo0bgtyFX3K6dm8k=/3/fill-475x300/Innovation_LeadershipSMALL.original.jpg?v=061f2c7e48685bdf841f9feb96fa340876626ee1
