### ISSUE TITLE
US5 As a learner, I want access to a statement of my payment status, so that I can get my visa or present to my company for reimbursement.

### ISSUE THREAD

**Issue by pdpinch** [mitodl/bootcamp-ecommerce#8]
This is a browser view, suitable for printing. It should contain the following information:

- learner's full name
- learner's email
- name of bootcamp
- name of klasse (?)
- dates of klasse
- a list of each payment, with:
  - amount paid
  - date of payment
  - name of payer
- total paid
- total cost of bootcamp
- remaining balance

**Comment by giocalitri** [comment]
What's the content for this?

**Comment by pdpinch** [comment]
brainstorming: 

- learner's name
- learner's email
- name of bootcamp
- name of klasse (?)
- dates of klasse, if we have it (I don't think we do)
- a list of each payment, with:
  - amount paid
  - date of payment
  - name of payer (if possible)
- total balance
- total cost of bootcamp
- remaining balance

@Ferdi what do you think? 

We should update the description when we finalize.

**Comment by Ferdi** [comment]
Sounds good.  Btw, we should have klass date.

**Comment by pdpinch** [comment]
@gsidebo @giocalitri what needs to happen to make this work? Is this already covered in the API, and we just need the front-end?

**Comment by giocalitri** [comment]
It should be already covered by the rest APIs I wrote last week.
In the front end we probably need another view where to show this. Not sure how to format the info to be easily printable.

**Comment by gsidebo** [comment]
I'm starting work on this now. A few questions/comments right off the bat (based on [this design](https://projects.invisionapp.com/share/SFBD1T7DW#/screens/229971320)):

1. An address is shown in this statement. We don't store that information currently. Assuming we still want to capture that information, would it make more sense to store that as a property of a `Bootcamp` or a `Klass`? 
1. The title shown in the "Bootcamp" section of that design should probably be "<Bootcamp title> - <Klass title>" as we have it in other areas of the app. 
1. I think the "Bootcamp Name" column of the statement is redundant. As far as I can tell, this statement is related to a specific `Klass`, so there will only ever be one `Klass` represented in the statement, and therefore only one `Klass` title.

**Comment by gsidebo** [comment]
@pdpinch @Ferdi @roberthouse54 ^^^

**Comment by Ferdi** [comment]
Great go for it !    No need to prompt for printing either.
