### ISSUE TITLE
dropzone library not accessible

### ISSUE THREAD

**Issue by aliceriot** [mitodl/bootcamp-ecommerce#815]
the react-dropzone-uploader library we're using is not keyboard accessible. see this issue: https://github.com/fortana-co/react-dropzone-uploader/issues/10

we probably want to either decide to modify it or switch to `react-dropzone`, which does seem to be keyboard-accessible (try out the examples here: https://react-dropzone.js.org/)

**Comment by gsidebo** [comment]
The author suggested that a custom input component could be passed in. Worth looking into before we switch libraries. This library does give us quite a lot on top of `react-dropzone`

**Comment by gsidebo** [comment]
Closing in favor of https://github.com/mitodl/bootcamp-ecommerce/issues/901
