### ISSUE TITLE
Enable fixed position and auto-dismiss user alerts 

### ISSUE THREAD

**Issue by gsidebo** [mitodl/bootcamp-ecommerce#824]
We have user notifications that appear directly beneath the nav bar.

<img width="943" alt="ss 2020-06-29 at 18 42 13 " src="https://user-images.githubusercontent.com/14932219/86063164-45c9a800-ba38-11ea-99b5-2f7fa562615c.png">

We're using this same notification element to show some error/success messages to users (#906). This is less than ideal for a few reasons:
1. These notifications are not in fixed position, so if the user is scrolled down on the page, they will not see this notification unless they scroll up, and they will not see it at all if they navigate to another page.
1. If the user has a drawer open, the overlay renders above the notification element and almost completely hides it.

We will implement fixed position notifications for these types of messages.

### Acceptance criteria
- Site-wide notifications (sourced from the CMS) still shown as they were before (under the nav bar, not in fixed position, rendered under the overlay if a drawer is open)
- Error/success messages that are rendered in an alert/notification now shown in fixed position at the bottom of the page (i.e.: they stay at the bottom of the page when scrolling), and are shown above all other elements. 

### Nice to have
- Success messages auto-dismiss after a short period of time

**Comment by abdulkdawson** [comment]
@gsidebo here is a link to the success message mock. Tell me if this works. [https://projects.invisionapp.com/d/main?origin=v7#/console/19928472/424654864/preview?scrollOffset=1544.4444580078125](https://projects.invisionapp.com/d/main?origin=v7#/console/19928472/424654864/preview?scrollOffset=1544.4444580078125)

**Comment by asadiqbal08** [comment]
I need one clarification over the 1st acceptance criteria. 

> Site-wide notifications (sourced from the CMS) still shown as they were before (under the nav bar, not in fixed position, rendered under the overlay if a drawer is open)

what actually, is meant by this -- "rendered under the overlay if a drawer is open"

**Comment by pdpinch** [comment]
> what actually, is meant by this -- "rendered under the overlay if a drawer is open"

There is a drawer UI on the /applications dashboard that opens on the right side of the page:

<img width="1726" alt="image" src="https://user-images.githubusercontent.com/430126/89781094-aab8f900-dae0-11ea-8fa5-77ca4fcc58c1.png">

The toast / user alert message should appear above the drawer.

**Comment by asadiqbal08** [comment]
If the msg will appear above the drawer then will it not hide the upper portion of the drawer ?
