### ISSUE TITLE
Decide on loading UI

### ISSUE THREAD

**Issue by gsidebo** [mitodl/bootcamp-ecommerce#847]
**Acceptance criteria for this issue:** Decision made (and, if possible, invision designs added) for the UI in the categories below

### Buttons
We have many buttons that result in an HTTP request when clicked. We need to decide what should happen when a button has been clicked and a request is in progress. Note that we have some buttons with "normal" button styling, and we also have the "Expand +" button on the app dashboard which loads data via HTTP, but looks like normal text.

Library that we could add, or take some inspiration from: https://loading.io/button/

### Page load
We have several pages that ask our API for data as soon as they load. We never decided on what to display while those requests are in progress, so on most/all of those pages, the user will see nothing during requests that take a long time for whatever reason. The simplest solution is just to display "Loading..." in plain text where the page body would otherwise be, but we might want something more sophisticated.

**Comment by gsidebo** [comment]
@abdulkdawson @Ferdi Let me know what you think

**Comment by abdulkdawson** [comment]
@gsidebo thank you for providing these examples of loading options. I agree we need to implement one for buttons and one for the page itself. The "ld-over" for the buttons would work as well as the "ld-over-full" for the page load.
