### ISSUE TITLE
Remove tox

### ISSUE THREAD

**Issue by gsidebo** [mitodl/bootcamp-ecommerce#937]
We have moved away from using tox to run our test suite for web apps. We should do the same here. Here's a PR from mitxpro where we removed tox: https://github.com/mitodl/mitxpro/pull/44

**Comment by pdpinch** [comment]
@mbertrand @gsidebo can this be closed?

**Comment by mbertrand** [comment]
Yes

**Comment by pdpinch** [comment]
Can this be closed?
